[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods",
    "consider-using-from-import",
    "arguments-renamed",
    "unused-argument",
    "no-member",
    "import-error",

]

[tool.black]
line-length = 130
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true
atomic = true
profile = "black"
line_length = 130
skip_gitignore = true